public enum Fruit
{
	APPLE,PEAR,PEACH,APRICOT,CHERRIES,GRAPES,PLUMS,STRAWBERRIES,RASPBERRIES,BLACKBERRY,BLUEBERRY,CRANBERRY,WATERMELON,AVOCADO,ORGANGE,TANGERINE,LEMON,LIME,GRAPEFRUIT,PINEAPPLE,MANGO,PAPAYA,POMEGRENATE,KIWI,BANANAS,COCONUT,QUINCE,
}